
-- CREATE AND SELECT DATABASE
CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

-- CREATE TABLE: AUTHORS
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
  AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(215) NOT NULL,
  PRIMARY KEY (AUTHOR_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

-- CREATE TABLE: BOOKS
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
  BOOK_ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRICE DOUBLE,
  PUBLICATION_DATE DATE,
  PRIMARY KEY (BOOK_ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

-- CREATE TABLE: CUSTOMERS
DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215) NOT NULL,
  ADDRESS TEXT,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

-- CREATE TABLE: ORDERS
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
  ORDER_ID INT NOT NULL AUTO_INCREMENT,
  ORDER_DATE DATE,
  CUSTOMER_ID INT NOT NULL,
  PRIMARY KEY (ORDER_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

-- CREATE TABLE: ORDER_DETAILS
DROP TABLE IF EXISTS ORDER_DETAILS;
CREATE TABLE ORDER_DETAILS (
  ORDERDETAILID INT NOT NULL AUTO_INCREMENT,
  QUANTITY DOUBLE,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  PRIMARY KEY (ORDERDETAILID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;
